name: dw-gan
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - anyio=2.2.0
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=20.3.0
  - babel=2.9.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - bleach=3.3.0
  - brotlipy=0.7.0
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - colorama=0.4.4
  - contextvars=2.4
  - cryptography=3.4.7
  - cudatoolkit=10.1.243
  - dataclasses=0.8
  - decorator=5.0.7
  - defusedxml=0.7.1
  - deprecation=2.1.0
  - entrypoints=0.3
  - hdf5=1.8.20
  - idna=2.10
  - immutables=0.15
  - importlib-metadata=4.0.1
  - intel-openmp=2020.2
  - ipykernel=5.5.3
  - ipython=5.8.0
  - ipython_genutils=0.2.0
  - jinja2=2.11.3
  - jpeg=9b
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter-packaging=0.9.2
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - jupyter_server=1.6.4
  - jupyterlab=3.0.14
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.4.0
  - libopencv=3.4.2
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.1.0
  - lz4-c=1.9.3
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - nbclassic=0.2.7
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - nest-asyncio=1.5.1
  - ninja=1.10.2
  - notebook=6.3.0
  - numpy-base=1.19.2
  - opencv=3.4.2
  - openssl=1.1.1k
  - packaging=20.9
  - pandoc=2.13
  - pandocfilters=1.4.2
  - pickleshare=0.7.5
  - pip=21.0.1
  - prometheus_client=0.10.1
  - prompt_toolkit=1.0.15
  - py-opencv=3.4.2
  - pycparser=2.20
  - pygments=2.8.1
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.6.13
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytorch=1.4.0
  - pytz=2021.1
  - pyzmq=22.0.3
  - requests=2.25.1
  - scipy=1.5.2
  - send2trash=1.5.0
  - setuptools=52.0.0
  - simplegeneric=0.8.1
  - six=1.15.0
  - sniffio=1.2.0
  - sqlite=3.35.3
  - terminado=0.9.4
  - testpath=0.4.4
  - tomlkit=0.7.0
  - tornado=6.1
  - traitlets=4.3.3
  - typing_extensions=3.7.4.3
  - urllib3=1.26.4
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - click==7.1.2
    - cycler==0.10.0
    - dominate==2.4.0
    - flask==1.1.2
    - flask-uploads==0.2.1
    - flask-wtf==0.14.3
    - itsdangerous==1.1.0
    - kiwisolver==1.3.1
    - matplotlib==3.3.4
    - numpy==1.16.4
    - pillow==8.2.0
    - torchfile==0.1.0
    - torchvision==0.5.0
    - visdom==0.1.8
    - websocket-client==0.58.0
    - werkzeug==0.16.0
    - wtforms==2.3.3
